### PR TITLE
Change tab to space 4

### PR DESCRIPTION
**Pull request by amay077**

### CODE REVIEW

**Comment by deextercz** [comment]
Hello what is LF of these files?
I am not able to reset them, I think it is UNIX LF instead of windows.
capture

**Comment by amay077** [comment]
Oh that's mistake.
CR LF is wrong, Only LF is correct.
I'll fix it.

**Comment by deextercz** [comment]
@amay077 thank you.

**Comment by amay077** [comment]
Fixed it!
https://github.com/amay077/Xamarin.Forms.GoogleMaps/commit/8a837bbca5f2f262b0602c77f164ddb6e84e7192

**Pull request merged**
