### PR TITLE
Improved Binding Support

### LINKED ISSUE #519: Improved Binding Support
### SUMMARY

Working with the Map control should allow easy binding to a data set with a DataTemplate. This should work similar to a ListView in which you can bind to a generic set of data with a DataTemplate that produces a Pin to add to the controls Pin collection.

### DETAILS

Two bindable properties should be added:

- ItemsSource
- ItemTemplate

```xml
<maps:Map Items="{Binding MyLocations}">
  <maps:Map.ItemTemplate>
    <DataTemplate>
      <maps:Pin Label="{Binding Name}" 
                IsDraggable="false"
                Icon="{Binding SomeProp,Converter={StaticResource MyIconConverter}}">
        <maps:Pin.Position>
          <maps:Position Latitude="{Binding Latitude}"
                         Longitude="{Binding Longitude}" />
        </maps:Pin.Position>
      </maps:Pin>
    </DataTemplate>
  </maps:Map.ItemTemplate>
</maps:Map>
```

In addition, an event and Command should be added in the spirit of when a Pin is Selected.

- ItemSelected (event)
- ItemSelectedCommand 

When a Pin is selected the ItemSelected event should invoked and the Command executed with the BindingContext of each passed to them.

### PLATFORMS

- [X] Android
- [X] iOS
- [X] UWP

### PR DESCRIPTION
**Pull request by dansiegel**
# Description

Adds ItemsSource with ItemTemplate and SelectedItemCommand/Event.
fixes #519

### CODE REVIEW

**Comment by dansiegel** [comment]
Happy to add it to the sample. As for the other issues you brought up.

>- ItemsSource -> PinsSource
>- ItemTemplate -> PinTemplate
>- ItemSelectedCommand -> PinSelectedCommand

The naming was done to be consistent with other Xamarin.Forms API's such as the ListView and TabbedPage. Also it is only loosely tied to Pins, so naming it Pin{whatever} would get confusing as you would may lead people to thinking it is an actual Pin. The items bound to the ItemsSource are not necessarily Pins. In fact if you're following an MVVM design they should never be Pins. 

> Because I want to follow original Xamarin.Forms.Maps specification 

If you look at the Xamarin.Forms.Maps codebase you'll see that the most of the files haven't even been touched since the initial import 2 years ago, a few classes has some very minor tweaks around internals and what they're visible to. Beyond that there have been no changes making it stagnant. Point being the Xamarin.Forms.Maps API was done in an era when developers were writing all of their Pages in code. Today with XAML and MVVM design being the prominent design pattern developers have different needs.

> Seems SelectedPinChanged(exists) is the same as SelectedItemChanged(new).
>
> Do you need SelectedItemChanged and SelectedItemChangedEventArgs?

These actually aren't duplicates. They are similar in concept, but not duplicate. The SelectedPinChanged raises the Pin, where the SelectedItemChanged as well as the ItemSelectedCommand are both focused on the Item. The item is a abstract concept that would be in the ItemsSource and used as the BindingContext of the Pin rather than the Pin itself. Whereas the SelectedPinChanged is all about providing the Pin itself.

**Comment by dansiegel** [comment]
worth noting, if I add the sample it won't build given that you are referencing the published NuGet instead of the code. I'm still happy to add it if that's what you want.

**Comment by amay077** [comment]
You can use [Xamarin.Forms.GoogleMaps_with_sample.sln](https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/Xamarin.Forms.GoogleMaps/Xamarin.Forms.GoogleMaps_with_sample.sln) what is all projects contained solution (not using nuget) .

I hope you add sample code to it. :wink:

**Comment by galadril** [comment]
+1

I've also extended the GoogleMaps project to bind more items:
Pins
Polylines
CameraPosition

So i can use this map component like:

```

    <!--  Map  -->
         <cntrl:ExtendedMap
            x:Name="map"
            Grid.Row="0"
            CameraPosition="{Binding CameraPosition}"
            IsVisible="{Binding Status, Converter={StaticResource StatusConverter}, ConverterParameter=Data}"
            MapType="Street"
            Pins="{Binding Pins}"
            Polylines="{Binding Polylines}" />

```

So if your extending the bindings.. :) Please do Pins, Polylines and CameraPosition as well 👍

**Comment by dansiegel** [comment]
@amay077 are you good with the addition of Bindable Pins, Polylines, and CameraPosition?
Also I'm going to update the sample app so the platforms are using PackageReferences instead of the older package.config style... it'll be nicer to restore from the global cache rather than duplicating a cache for the project. 
If you're ok with it I can add the Mobile.BuildTools package as well to handle the injection of the API Key's

**Comment by seanyda** [comment]
I have also extended this control to handle the same thing but I write the UI in C#.
```
new Map {
                        Behaviors = {
                            new UpdateRegionBehavior {
                                Region = new Binding("Region")
                            },
                            new BindingPolylinesBehavior {
                                ItemSource = new Binding("TrackingInfo")
                            },
                            new BindingPinsBehavior {
                                ItemSource = new Binding("MapPins")
                            }
                        }
                    },
```

It would be neat to see something like this merged into master :)

**Comment by andreinitescu** [comment]
@dansiegel It's not clear to me how the `ItemTemplate` is supposed to work.
Looking at your implementation [here](https://github.com/amay077/Xamarin.Forms.GoogleMaps/pull/521/commits/a4a0432cadebde5c7e10a911e539c20c962cab06#diff-2393e2d73f7e1b05252a69d947ee0584R548) you expect the `DataTemplate` to be materiazed into a `Pin`:


            if (content is Pin pin)
            {
                Pins.Add(pin);
            }
            else
            {
                Forms.Internals.Log.Warning("ERROR", $"The DataTemplate returned a '{content.GetType().Name}' instead of expected type 'Pin'.");
            }

But `Pin` cannot be used in XAML within a `DataTemplate`, the following won't compile:

            <PinTemplate>
                <DataTemplate>
                    <Pin />
                </DataTemplate>
            </PinTemplate>

Could you please give some info on how it needs to work? Thanks!

**Comment by amay077** [comment]
Sorry I'm very very late.
I merged this PR but I will refactor according like @andreinitescu's [PR](https://github.com/xamarin/Xamarin.Forms/pull/4269).

**Pull request merged**
