### PR TITLE
infowindow long pressed implemented.

### PR DESCRIPTION
**Pull request by samirkhatri**
I have implemented long press on infowindow, please review and request you to merge so I can continue with my project by using your repo and get all updates.

### CODE REVIEW

**Comment by amay077** [comment]
#308

**Comment by amay077** [comment]
Looks great!

Could you add this feature to Out sample? (Like ``Map.InfoWindowClicked``)
https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/XFGoogleMapSample/XFGoogleMapSample/PinsPage.xaml.cs#L143

**Comment by samirkhatri** [comment]
Sure, let me do it, Also I could not implement/test this in UWP.

**Comment by amay077** [comment]
Thanks. 👍 
Please [set your collect email address](https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/CONTRIBUTING.md#getting-started) to github profile.
I hope joined you to our [contributors page](https://github.com/amay077/Xamarin.Forms.GoogleMaps/graphs/contributors).

**Comment by samirkhatri** [comment]
Sorry for that, I have just set the email address. Do i need to do anything now ?

**Comment by amay077** [comment]
Could you make a something new commit?

**Comment by amay077** [comment]
You became our contributor! Thanks!

**Pull request merged**
