### PR TITLE
Sample config changes

### PR DESCRIPTION
**Pull request by JKennedy24**
Changed Android and UWP samples to deploy,

Changed UWP sample to x86 instead of ARM, makes it easier to run

### CODE REVIEW

**Comment by deextercz** [comment]
Please try to squash you commit into 1, it is easier to revert if it has an error.
https://makandracards.com/makandra/527-squash-several-git-commits-into-a-single-commit

**Comment by JKennedy24** [comment]
All changes should be in the last commit, The first 4 commits were me trying to bring my Master branch in sync with the master branch here

**Comment by deextercz** [comment]
What is purpose of this pullrequest?

**Comment by JKennedy24** [comment]
This was just to change the config settings of the Sample project to make it easier to use

- Changed Android and UWP samples to deploy,
- Changed UWP sample to x86 instead of ARM

**Pull request merged**
