### PR TITLE
Pin Offset

### PR DESCRIPTION
**Pull request by deextercz**

### CODE REVIEW

**Comment by deextercz** [comment]
I dobt kniw how to test it please try it.

**Comment by amay077** [comment]
Sorry, I'm late.
I'll try your implementations.

**Comment by amay077** [comment]
Thanks @deextercz,
I hope listed bellow:

* Add sample code for your additional function
* Test your code by yourself

I added some [implementation](https://github.com/amay077/Xamarin.Forms.GoogleMaps/commit/59a86ffbec084da61264d33de72fc9ab7e95b552) and [sample page](https://github.com/amay077/Xamarin.Forms.GoogleMaps/commit/444bf23ebaf0ed60f8b12fd59739a167d4fb192c). 👍

**Comment by deextercz** [comment]
Hello @amay077 I plan to do it in next month

**Pull request merged**
