### PR TITLE
Adds binding for MapRegion, PinsSource, CirclesSource, Commands,... - More MVVM

### PR DESCRIPTION
**Pull request by JeanCollas**
# Implements the logic to bind directly objects to the XAML map (MapRegion, PinsSource and CirclesSource)

## What has been done
- **MapRegion** Map property allows to initiate the map at the right place, and gets updated with the camera. MapRegion changes when the camera changes, and setting MapRegion moves the camera to this point. An event MapRegion_Changed is exposed for code-oriented programming.
- **MapSpanTypeConverter** type allows raw entries directly in XAML for MapSpan for position initialization. Formats available are "(Lat,Lng),LatDelta,LngDelta" or "(North,West),(South,East)".
- **PositionJsonConverter** to allow deserializing the **Position** type
- Interfaces have been created, that bound object should implement:
  - IPin
  - ICircle
  - ISegment
- **PinsSource** property is an observable collection of **IPin**, Interface allowing the user to abstract its logic from the Map Models. All Pins property are binded to this interface, so the user can update its models and see the modifications directly on the map (if he has implemented the INotify). More properties could be exposed to customize the pins.
- **CirclesSource** is an observable collection of **ICircle**.
- **SelectedItem** Is bound two ways to the selected pin (no more need to work with the map pins)
- **Pins animation** Pins can be animated on appear (pop only for iOS, many patterns for Android like drop, shake, etc, but not pop)
- **Geographical extensions**: some extensions to Position and Circle have been added to allow some "simple" geographic calculations answering:
  - Distance between two points
  - Orientation (bearing) of a segment
  - Is a point in a circle/disc?
  - Does a segment intersect a circle? (just for fun)
  - Translate a geographical point giving a direction (direction can be provided via an angle or a segment), useful to predict position knowing the speed for example. See sample CircleBinding.

## Comments
- Very easy to use, just bind a ObservableCollection<ISomething>
- 3 new samples show how to use these features
- The last sample (Properties Binding) shows the MapRegion, SelectedItem and PinsSource binding.
- The 1st Pin sample has been updated to show the raw MapSpan capacity.

## Remarks:
- VisibleRegion has been changed to MapRegion as the term did not fit for the "initiation". MapRegion handles modification and observation
- SelectedItem has been bound two ways with SelectedPin
- The collection binding could be easily extended to other shapes, it does not modify the existing code, just need to copy/paste one of the two region and set the correct types/properties, and create an interface.

This answers the issue posted earlier: https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues/150 

Enjoy

## Planned
- Get all geography out of the main project (to be able to add reference only to the geography project, without Xamarin.Forms dependency)
- Add more animations for iOS pins apparition
- Add custom buttons for zoom
- Add grouping behavior for pins
- Any other nice idea :)

### CODE REVIEW

**Comment by adamhill** [comment]
Any idea when this fix will land in master?

**Comment by JeanCollas** [comment]
@adamhill : I have developped it for my own needs (and a bit "just for fun" in samples). However we haven't discuss at all with @amay077 , if this dev fits its development view/style etc. Therefore it will probably require some testings by @amay077 before :)
However I use this branch for my own app and it works great, I will release a public version soon (the current live version of my app uses another solution, I have just migrated to this one because it was much more flexible to implement the binding logic).

**Comment by JeanCollas** [comment]
@adamhill I totally agree, that is why I implemented it, and it feels now so much easier to use!

**Comment by deextercz** [comment]
For me it does not work on Android phone
01-02 23:12:41.162 D/Mono    (16729): Searching for '__android_log_print'.
01-02 23:12:41.162 D/Mono    (16729): Probing '__android_log_print'.
01-02 23:12:41.163 D/Mono    (16729): Found as '__android_log_print'.
01-02 23:12:41.182 I/MonoDroid(16729): UNHANDLED EXCEPTION:
01-02 23:12:41.227 I/MonoDroid(16729): System.MissingMethodException: Method **'Xamarin.Forms.GoogleMaps.Map.set_VisibleRegion' not found.**
01-02 23:12:41.228 I/MonoDroid(16729):   at Xamarin.Forms.GoogleMaps.Android.MapRenderer.OnCameraChange (Android.Gms.Maps.Model.CameraPosition pos) [0x00007] in <d22a815836d74048afc23e1087622256>:0 
01-02 23:12:41.228 I/MonoDroid(16729):   at Android.Gms.Maps.GoogleMap+IOnCameraChangeListenerInvoker.n_OnCameraChange_Lcom_google_android_gms_maps_model_CameraPosition_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_position) [0x00011] in <cede2ee4138a48bb98b62dcaee115663>:0 
01-02 23:12:41.228 I/MonoDroid(16729):   at (wrapper dynamic-method) System.Object:336195f3-6fc8-4201-b615-12f5f6bfed90 (intptr,intptr,intptr)
01-02 23:12:41.258 D/Mono    (16729): DllImport searching in: '__Internal' ('(null)').
01-02 23:12:41.258 D/Mono    (16729): Searching for 'java_interop_jnienv_throw'.
01-02 23:12:41.258 D/Mono    (16729): Probing 'java_interop_jnienv_throw'.
01-02 23:12:41.259 D/Mono    (16729): Found as 'java_interop_jnienv_throw'.
An unhandled exception occured.

Thread finished: <Thread Pool> #4
01-02 23:12:49.264 D/Mono    (16729): [0x69740c68] worker finishing
The thread 'Unknown' (0x4) has exited with code 0 (0x0).
01-02 23:12:58.494 D/dalvikvm(16729): threadid=15: bye!
01-02 23:12:58.496 E/mono    (16729): 
01-02 23:12:58.496 E/mono    (16729): Unhandled Exception:
01-02 23:12:58.496 E/mono    (16729): System.MissingMethodException: Method 'Xamarin.Forms.GoogleMaps.Map.set_VisibleRegion' not found.
01-02 23:12:58.497 E/mono-rt (16729): [ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: Method 'Xamarin.Forms.GoogleMaps.Map.set_VisibleRegion' not found.
In mgmain JNI_OnLoad

But I dont get this everywhere was VisibleRegion renamed to MapRegion

**Comment by JeanCollas** [comment]
"But I dont get this everywhere was VisibleRegion renamed to MapRegion"
You are right. 
I haven't tried the samples I have added for a while, but they should work.

**Comment by deextercz** [comment]
I tried your last commit and results are still same :-(

**Comment by JeanCollas** [comment]
Have you tried the samples? 

The last commit was just a crash-proof fix on another issue

**Comment by deextercz** [comment]
Nope, I am not able tu run sample because it is telling me something with colorAccent.

**Comment by amay077** [comment]
This is great work!
I can not review these because it has very big changes.
And I hope keep backward compatibility in X.F.GoogleMaps v1.x.

If you want to use MVVM like data bindings, I recommend to use [Xamarin.Forms Behaviors](https://developer.xamarin.com/guides/xamarin-forms/behaviors/).

@nuitsjp is developing [Xamarin.Forms.GoogleMaps.Bindings](https://github.com/nuitsjp/Xamarin.Forms.GoogleMaps.Bindings/) that provides useful Xamarin.Forms behaviors for data binding with XAML.

If you have other features, please you contain minimum and atomic file changes in your Pull-request.

**Comment by deextercz** [comment]
Will be this merged to master or it was already merged?

**Comment by amay077** [comment]
No, I rejected this PR because [this](https://github.com/amay077/Xamarin.Forms.GoogleMaps/pull/151#issuecomment-270384632).
I have no plan to merge this **BIG** changes.

**Comment by deextercz** [comment]
If @JeanCollas will not split to smaller pulk requests I will try it

**Comment by JeanCollas** [comment]
You can do it, actually you just need to follow the commits.
I am not so good at merging different repositories, and continued to work on the branch as nobody was looking at it. 

I think the only 'conflict' with the branch of this repository is the VisibleRegion that I renamed to MapRegion. To simplify this issue, you can just duplicate the property 'VisibleRegion' as a mirror of the 'MapRegion', and trigger a OnPropertyChanged("VisibleRegion") on MapRegion change.

**Pull request closed without merging**
