### PR TITLE
[WIP]Update Google play service pakcages

### PR DESCRIPTION
**Pull request by amay077**
ref #239

### CODE REVIEW

**Comment by amay077** [comment]
I updated Google play service packages, but raises some build errors:

* Polygon.Holes became readonly
* Polygon.SetHoles argument is ``IList<LatLng>`` but expect arg is ``IList<IList<LatLng>>``. It it bug?
* MapView.Map is deleted

Thus I think difficultly for support both Google play services v29.x and v42.x.

**Comment by deextercz** [comment]
I think we can fork branches, master should continue with supporting new
services and same old_master should have older versions and if it will be
possible merge request could be merged to both.

po 27. 3. 2017 v 18:48 odesílatel amay077 <notifications@github.com> napsal:

**Comment by fcallejon** [comment]
There is a new Xamarin Google Play Services published.
I've tested it in my fork and looks well.

**Comment by amay077** [comment]
I'll re-create new PR.

**Pull request closed without merging**
