### PR TITLE
Added EnableTraffic booleans to UWP

### PR DESCRIPTION
**Pull request by JKennedy24**
Added Enable Traffic Boolean to UWP

### CODE REVIEW

**Comment by JKennedy24** [comment]
I have no idea what the changes to the .sln file are. Obviously github thinks there have been some. Not any that I'm aware of making

**Comment by JKennedy24** [comment]
@amay077  did you mean to merge the .csproj and .sln files in this pull request?

**Comment by amay077** [comment]
I don’t feel like edit .csproj and .sln files.
Alternately, I reverted .csproj and .sln file changes after merge.
I think that's a bad idea. Because commit history does not clean.

**Comment by amay077** [comment]
@JKennedy24,

Your commit user and email are different with your GitHub account.



Could you set GitHub's user and email to local repository?

**Comment by deextercz** [comment]
Hello,
that was my commit, I was on another computer and I did not realize that.

**Comment by amay077** [comment]
Sorry, Correctly is this.



I merged PR that contains @JKennedy24 's commits 
but @JKennedy24 is not added [Contributors](https://github.com/amay077/Xamarin.Forms.GoogleMaps/graphs/contributors).
Because your email was different from GitHub account.

I hope shown your contribution.

**Comment by JKennedy24** [comment]
@amay077  I think I fixed that, I don't mind if my contributions dont show up, I'm just happy to be using the library

**Comment by amay077** [comment]
Thanks @JKennedy24,
I am glad that many people contributions.

**Pull request merged**
