### PR TITLE
[WIP]Added UWP Map Clicked

### PR DESCRIPTION
**Pull request by JKennedy24**
Added Click Event to UWP Map

### CODE REVIEW

**Comment by amay077** [comment]
Thank you for your contribution.
If this is still work in progress then please change to the title "[WIP]Added UWP Map Clicked".

**Comment by JKennedy24** [comment]
@amay077 I am very new to github so please tell me if I am doing anything wrong.
Things I have added to UWP so far:
- Map Click events
- Custom Icons
- Enable Traffic

I am going to try add Custom map tile layers over the next week or so

**Comment by JKennedy24** [comment]
Bug in map control affecting UWP map tiles loaded from local resources. info about it here: [http://stackoverflow.com/questions/39420071/bing-maps-not-loading-tiles-from-local-app-data](http://stackoverflow.com/questions/39420071/bing-maps-not-loading-tiles-from-local-app-data). May be able to work around it by implementing Image tile sources

**Comment by amay077** [comment]
Hi @JKennedy24,

> I am very new to github so please tell me if I am doing anything wrong.

You should separate to feature per branch.
You commits all features to main branch, so it is big changes and I review it difficultly.

I hope you make feature/branch listed are follows,

* UWP Map Clicked -> uwp_map_clicked branch
* UWP Custom Icons -> uwp_custom_icons branch
* UWP Enable Traffic -> uwp_enable_traffic branch

and send me pull-request each branches.

**Comment by deextercz** [comment]
Maybe better will be create issue, describe briefly what you want to do and after that create branche with issue number like issue_117

**Comment by JKennedy24** [comment]
I must be honest. I dont know how to branch my project and group my commits into branches. Havent they all been commited to the main branch so I'd have to undo them or something?

So far I have only changed the UWP project. Essentially all I've done is add the PinLogic and TileLayerLogic and flesh those two classes out for UWP and removed the old pin logic from MapRenderer. I am still working on Image Tile layers working

As for adding enable traffic that is 1 line.

Hope that helps

**Comment by deextercz** [comment]
For this time i think we can review this as it is.
Make your changes works and we will see this.
čt 24. 11. 2016 v 10:04 odesílatel JKennedy24 <notifications@github.com>
napsal:

**Comment by atsushieno** [comment]
Let me dive in as @amay077 wanted some English help, and I can share experiences from github collaboration in community development (I'm from mono team).

Merging such set of incomplete changes is problematic to EVERYONE ELSE, for the following reasons:

- It breaks commit atomicity. Unless there is any other reasons, changes should be "atomic" i.e. one single commit. Otherwise, what happens if the changes were regressive and have to be reverted? Especially when those changes are sparse and have different commits in-between when they were merged? They became more difficult to revert and thus they will mess everything.
  - This especially applies to changes like: "reafactored XXX" -> if you have been making incomplete changes or reverting ones, they should not be seen in the final merged tree. Just get "git diff master [your feature branch]" and apply the changes from master again.
- Broader changes without reason brings worse chances for others conflicts. What do you feel if your ongoing changes has conflicts with someone else's changes that were pointless? You'd get frustrated.

----

Therefore, we encourage people to learn about our common workflow. At github it is called "github flow":
https://guides.github.com/introduction/flow/index.html

What it basically suggests is:

- Create a git "branch" and develop your additional feature on that branch.
- Commit and push to your "fork" tree. You already have it! Just do not push it from master (as it will mess your next contributions).
- Then submit a PR.

You can review what changes you have been making on your tree by running:

    git diff XXXXXXX HEAD >changes.diff

where XXXXXXX is the commit hash when you started making your changes i.e. the previous one before your first change (note that the diff file would contain just file names for binaries such as .png).
Once you got the diff, you can go back to the commit by:

    git checkout XXXXXXX

and then create a new feature branch from there:
    git branch add-uwp-map-clicked

Then, switch to the branch as:

    git checkout add-uwp-map-clicked

and apply your changes you made, by using 'patch' tool:

    patch -i changes.diff -p1

And copy binary files that you have added for the new feature.

Then make a git commit. All of your changes can be now done in a single commit!

In case you made some insufficient commits, you can still "fix" it by adding '--amend' argument to a new git commit operation. It will "fix up" (merge the new changes to) the last commit, instead of making a new commit.

Then you can push your changes to your github repo, but make sure to push to your feature branch e.g.:

    git push [remotename] add-uwp-map-clicked

It will push your changes to the feature branch, not master.

Once you are done with above, you can go back to your master (actually you can do so at any time, I just don't want to mess the workflow by telling so ;-)

----
ONCE you are done with everything (i.e. your changes get successfully merged), then I'd suggest to "roll back" your master to the original (now you'd have to deal with git merge conflicts every time you "git pull" in the changes). You can run 'git reset HEAD^' on your master branch to "reset" one commit. Actually, ^^ indicates to rollback two commits, ^^^ for three... Once your rollback is done down to the "original" master tree (i.e. no more changes from you), then your next "git pull" operation will not cause merge conflicts anymore. Oh, and you can even "fix" the changes you had made in the past, by "git push -f [yourremote] master". Usually -f it should not be used (as it is dangerous!), but in case you indeed make changes it is useful. Your "master" now has extraneous changes, you'd like to fix it at some stage.

**Comment by atsushieno** [comment]
And one more thing: if you have changes for different purpose (e.g. to me adding clicked even and adding pins look different purpose or level of changes), they should be in different feature branches (i.e. you should make two different branches). If one is dependent on another feature, you can create another PR later.

**Comment by JKennedy24** [comment]
@atsushieno  Thanks for the info. I think what I'm going to do is close this and start again. obviously I wont have to work out what to do so it shouldnt take too long, I'm going to take your comments on board

**Pull request closed without merging**
