### PR TITLE
Fixing Java.Lang.NullPointerException: bitmap

### PR DESCRIPTION
**Pull request by deextercz**

### CODE REVIEW

**Comment by deextercz** [comment]
I am not sure if this also occurs on iOS and I am not able to find out so it is fixing just on android.
If I find out that it occurs also on iOS I will push another pullrequest

**Comment by deextercz** [comment]
It probably occurs only on Android. @amay077 could you review this PR please?

**Comment by amay077** [comment]
Sorry I'm late.
Merged it, thanks!

**Comment by amay077** [comment]
ref #246

**Comment by amay077** [comment]
ref #235

**Pull request merged**
