### PR TITLE
Caching capabilities for android project

### PR DESCRIPTION
**Pull request by Matiszak**
I also added commit with new sample rendering 1600 pins with caching.

### CODE REVIEW

**Comment by amay077** [comment]
ref #497

**Comment by amay077** [comment]
Thanks @Matiszak ,
You became a contributor!

**Comment by samirbittar** [comment]
Very interested in when this'll be pushed into NuGet!

**Comment by amay077** [comment]
I just released to https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/3.0.0-beta6 .
Just a moment for indexed to nuget.org.

**Pull request merged**
