### PR TITLE
EventHandler to PinClickedEvent

### PR DESCRIPTION
**Pull request by deextercz**

### CODE REVIEW

**Comment by deextercz** [comment]
#107

**Comment by amay077** [comment]
I rejected this PR because this is breaking changes.

**Comment by deextercz** [comment]
Could you please briefly describe what are breaking changes, that I could investigate and fix it?

**Comment by amay077** [comment]
```
pin.Clicked += (object sender, EventArgs e) =>
{
    int a = 0;
};
```

This code is works fine for previous X.F.GoogleMaps version.
But It has compile errors after apply this PR. 

* ``Pin`` does not contain a definition for ``Clicked``
* declared as type ``EventArgs`` but should be ``PinClickedEventArgs``

In my plan,

1. Keep ``event EventHandler Pin.Clicked`` with ``[Obsolete]`` attribute in X.F.GoogleMaps ver 1.x
2. In X.F.GoogleMaps ver 2.x, I will delete Pin.Clicked

I'm  adopting [Semantic Versioning](http://semver.org/).

**Pull request closed without merging**
