### PR TITLE
Added FromEncodedString for Polylines

### PR DESCRIPTION
**Pull request by galadril**
As discussed in this issue / feature request:
https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues/471

You can now create a Polyline from a encoded string by:

```
var polyline = Polyline.FromEncodedString("w`q~F|xbvO|a@{D");
```

### CODE REVIEW

**Comment by galadril** [comment]
Any ideas on this pull request?

**Comment by galadril** [comment]
??

**Comment by amay077** [comment]
Sorry I'm late.

Could you implement ``decode`` method?

**Comment by galadril** [comment]
Don't really get what you mean with decode method

**Comment by amay077** [comment]
I hope similar functions to ``google.maps.geometry.encoding.Geometry`` class in Google Maps JavaScript API.
That has two methods:

* Position[] DecodePath(string path)
* string EncodePath(Position[] path)

ref - https://developers.google.com/maps/documentation/javascript/reference/3/#encoding

**Comment by amay077** [comment]
I have not received the reply. 

I think "EncodedString and Polyline conversions" is common useful functions.
I hope it is (not depend X.F.GoogleMaps) individual library.

Thanks!

**Comment by galadril** [comment]
ok...

**Pull request closed without merging**
