### PR TITLE
[WIP]Disable MapToolbar in Android

### PR DESCRIPTION
**Pull request by amay077**
#80

### CODE REVIEW

**Comment by deextercz** [comment]
Your pullrequest could be usefull for many of users including me and I hope this will be soon merged, but have you considered about extracting this as method?

**Comment by amay077** [comment]
Sorry, I kept you waiting.
This is now merged.

**Comment by amay077** [comment]
Hi @deextercz,

I deployed [1.7.0-beta2](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/1.7.0-beta2).
Would you try it.

**Comment by deextercz** [comment]
Hello,
I just tested that and it looks like it is fixed now.

**Pull request merged**
